### ISSUE TITLE
tom

### ISSUE THREAD

**Issue by king-of-bypass** [S3lrius/Nimalathatep#2]
D:\0ctf\1shell\ms\1nim\2022-7-20\Nimalathatep-master>nim -d:release c .\nimalathatep.nim
Hint: used config file 'D:\nim\nim-1.6.6\config\nim.cfg' [Conf]
Hint: used config file 'D:\nim\nim-1.6.6\config\config.nims' [Conf]
..............................................................................................................................
D:\0ctf\1shell\ms\1nim\2022-7-20\Nimalathatep-master\nimalathatep.nim(84, 14) Warning: replace `..b` with `0..b`; .. is deprecated [Deprecated]
CC: stdlib_digitsutils.nim
CC: stdlib_assertions.nim
CC: stdlib_dollars.nim
CC: stdlib_widestrs.nim
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: stdlib_algorithm.nim
CC: stdlib_strutils.nim
CC: C:/Users/22601/.nimble/pkgs/winim-3.8.0/winim/winstr.nim
CC: stdlib_dynlib.nim
CC: stdlib_winlean.nim
CC: stdlib_times.nim
CC: stdlib_win_setenv.nim
CC: stdlib_os.nim
CC: stdlib_base64.nim
CC: C:/Users/22601/.nimble/pkgs/nimcrypto-0.5.4/nimcrypto/utils.nim
CC: C:/Users/22601/.nimble/pkgs/nimcrypto-0.5.4/nimcrypto/hash.nim
CC: C:/Users/22601/.nimble/pkgs/nimcrypto-0.5.4/nimcrypto/sha2.nim
CC: C:/Users/22601/.nimble/pkgs/nimcrypto-0.5.4/nimcrypto/rijndael.nim
CC: C:/Users/22601/.nimble/pkgs/nimcrypto-0.5.4/nimcrypto/bcmode.nim
CC: C:/Users/22601/.nimble/pkgs/nimcrypto-0.5.4/nimcrypto/sysrand.nim
CC: stdlib_sysrand.nim
CC: stdlib_random.nim
CC: nimalathatep.nim
Hint:  [Link]
Hint: gc: refc; opt: speed; options: -d:release
168311 lines; 10.432s; 145.148MiB peakmem; proj: D:\0ctf\1shell\ms\1nim\2022-7-20\Nimalathatep-master\nimalathatep.nim; out: D:\0ctf\1shell\ms\1nim\2022-7-20\Nimalathatep-master\nimalathatep.exe [SuccessX]

**Comment by S3lrius** [comment]
Fixed deprecated function in latest push https://github.com/S3lrius/Nimalathatep/commit/4b09c91664eab6127b482fd1244aa43b0d489186
