### ISSUE TITLE
Error: cannot open file: sysrandom

### ISSUE THREAD

**Issue by bloggins** [S3lrius/Nimalathatep#3]
Installed nimble windows via [chocolatey]
Upon compilation error "Error: cannot open file: sysrandom" occurs.
Same error occurs on Kali when nim is installed via [ChooseNim]
![1](https://user-images.githubusercontent.com/3010137/182651645-a1bebdf6-68a8-403f-bca8-ec6178c82859.png)

![2](https://user-images.githubusercontent.com/3010137/182652221-4d4c2d63-a11c-4787-98d7-84a95da3af46.png)

**Comment by S3lrius** [comment]
Do a nimble install sysrandom. Didn't put this in the repo but I'll add it now.

**Comment by bloggins** [comment]
Perfect thanks! worked.
