### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by localhosti** [S3lrius/Nimalathatep#5]
What am I doing wrong? I could not build the file
![photo_2022-08-22_07-41-02](https://user-images.githubusercontent.com/99039041/185855927-6ad88599-4dfd-4cc5-89bb-6ebaa5a17e4a.jpg)

**Comment by S3lrius** [comment]
You need to provide the outfile argument, such as exe, scr, etc.

**Comment by localhosti** [comment]
> You need to provide the outfile argument, such as exe, scr, etc.

![photo_2022-08-22_14-09-20](https://user-images.githubusercontent.com/99039041/185929087-260f1cfd-c1b5-4857-a360-e59f295944f0.jpg)

**Comment by localhosti** [comment]
Maybe you can correct the command

**Comment by S3lrius** [comment]
Example usage:
`.\nimalathatep.exe flsalloc beacon.bin exe`

Closing this issue, feel free to run` .\nimalathatep.exe help` for further usage instructions.
